name: Mapa de Procesos - Matriz

on: [push, workflow_dispatch] # workflow_dispatch permite ejecutarlo manualmente con un botón

jobs:
  procesos_division:
    # El nombre del job cambiará dinámicamente en el grafo visual
    name: División ${{ matrix.division }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Definimos las dos ramas de nuestro mapa de procesos
        division: [Software, Hardware]
    
    steps:
      # ==========================================
      # PROCESOS EXCLUSIVOS DE SOFTWARE
      # El estudiante puede agregar más steps aquí abajo
      # ==========================================
      - name: 💻 SW - Arquitectura y Diseño
        if: matrix.division == 'Software'
        run: echo "Creando diagramas UML y endpoints de la API."

      - name: 💻 SW - Desarrollo Backend
        if: matrix.division == 'Software'
        run: echo "Programando la lógica de negocio."

      # ==========================================
      # PROCESOS EXCLUSIVOS DE HARDWARE
      # El estudiante puede agregar más steps aquí abajo
      # ==========================================
      - name: ⚙️ HW - Diseño de PCB
        if: matrix.division == 'Hardware'
        run: echo "Diseñando las pistas y componentes electrónicos."

      - name: ⚙️ HW - Ensamblaje y Soldadura
        if: matrix.division == 'Hardware'
        run: echo "Soldando los microcontroladores en la placa."
